### ISSUE TITLE
Identify 5 potential referrees

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#23]
1. Fred Yeadon, Loughborough University, M.R.Yeadon@lboro.ac.uk, +44 (0)1509 226307
2. Alison Sheets, Nike Sports Research Lab, Beaverton, Oregon, alison.sheets@nike.com
3. Tron Krosshaug, Oslo Sports Trauma Research Center, tron.krosshaug@nih.no
4. J. R. Steele, University of Wollongong, jsteele@uow.edu.au
5. Gordon Robertson, University of Ottawa, dger@uOttawa.ca

UPDATE:

The people who have been contacted or will be contacted by F1000:

1. Fred Yeadon, Loughborough University, M.R.Yeadon@lboro.ac.uk, +44 (0)1509 226307
2. Alison Sheets, Nike Sports Research Lab, Beaverton, Oregon, alison.sheets@nike.com
3. Tron Krosshaug, Oslo Sports Trauma Research Center, tron.krosshaug@nih.no
4. J. R. Steele, University of Wollongong, jsteele@uow.edu.au
5. Gordon Robertson, University of Ottawa, dger@uOttawa.ca
6. Rick Hinricks, Arizona State University hinrichs@asu.edu
7. John Hutchinson Royal Veterinary College
8. Mike Pavol, Oregon State University
http://health.oregonstate.edu/people/pavol-mike
9.  Michael Hiley, Loughborough University M.J.Hiley@lboro.ac.uk
10. Karl  T. Bates (Department of Musculoskeletal Biology, University of Liverpool)
11. William I.     Sellers (Faculty of Life Sciences, University of Manchester)
12. Young-Hoo Kwon http://www.twu.edu/kinesiology/kinesiology-kwon.asp
YKwon@twu.edu
13. Chris Kirtley ckirtley@gmail.com
14. Jeffrey A. Weiss - Department of Bioengineering, and Scientific Computing and Imaging Institute, University of Utah, http://sci.utah.edu/~weiss/
15. Aymar de Rugy - Centre for Sensorimotor Performance, School of Human Movement Studies, The University of Queensland
16. Katherine R. Saul - Mechanical and Aerospace Engineering Department, North Carolina State 17. University, http://www.mae.ncsu.edu/faculty-staff/profile/katherine-saul/
17. Jennifer S. Wayne - Department of Biomedical Engineering, Virginia Commonwealth University, http://biomedical.egr.vcu.edu/faculty/wayne/
18. Giordano Valente, Istituto Ortopedico Rizzoli, Bologna, Italy (he may be a phd student, i just reviewed a paper by him)
19. A. Barre, Laboratory of Movement Analysis and Measurement (LMAM), EPFL, Lausanne, Switzerland
20. Stephane Armand: Willy Taillard Laboratory of Kinesiology, Geneva University Hospitals and Geneva University, Geneva, Switzerland. Electronic address: stephane.armand@hcuge.ch.

Those who have reviewed so far
- Alison Sheets

**Comment by monthubbard** [comment]
Alison Sheets at Nike.
Alison Sheets

**Comment by moorepants** [comment]
The two reviews are done and they've approved the article.
