### ISSUE TITLE
UML attributes have no explanation

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#32]
The first reviewer suggested that we explain the attributes in the UML diagram.

I responded on the F1000 Research with some explanation. Maybe we need to include that info in some way...but it could get verbose because there are a lot of attributes.

@chrisdembia @monthubbard

**Comment by moorepants** [comment]
@chrisdembia What should we do about this one?

**Comment by chrisdembia** [comment]
I'll add to the caption.

**Comment by moorepants** [comment]
I should have copied in the comment from the reviewer:

> My only minor suggestion is for the authors to add definitions for terms in Figure 4 that are not self-descriptive. For example, it is not clear what rel_center_of_mass and rel_inertia are defined relative to.

This seems to be more about what "relative" means.

**Comment by moorepants** [comment]
I just noticed that this docstring isn't very explicit about what "relative" means:

http://yeadon.readthedocs.org/en/latest/segment.html#yeadon.segment.Segment.calc_rel_properties

But that these are explicit:

http://yeadon.readthedocs.org/en/latest/segment.html#yeadon.segment.Segment.rel_center_of_mass
http://yeadon.readthedocs.org/en/latest/segment.html#yeadon.segment.Segment.rel_inertia
