### ISSUE TITLE
Notebook link seems broken

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#33]
This is the in paper:

http://nbviewer.ipython.org/github/chrisdembia/yeadon/blob/v1.2.0/examples/bicyclerider/bicycle_example.ipynb

We need to guarantee some persistency on this.

**Comment by moorepants** [comment]
Oh, nevermind, seems to work now.

**Comment by chrisdembia** [comment]
Fantastic turnaround time!

**Comment by moorepants** [comment]
:)
