### ISSUE TITLE
Explain why we didn't add more joints than Yeadon's original model

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#35]
From second reviewer:

> The authors modified some parts of the original model, why did they not add joint centers for ankles and wrists? This would give a better general behavior to the avatar.

**Comment by moorepants** [comment]
We were trying to stick as closely to Yeadon's implementation as possible. It should be relatively easy enough to subclass the segments and human to add in more joints as necessary. I guess we didn't do this because we were lazy. It would have been smart to add in ankle joints for the bike rider. But the foot is so goofy.

One explanation to not worry about this is the fact that the inertial difference in the whole body if the foot/hand had ankle/wrist joints is very small, probably negligible. It is only important when you are worried about those details of the body and then Yeadon's model is not suitable for just hand or foot models. Yeadon's model was not designed to predict the body segment inertia's on a individual basis but to predict whole body inertia.

**Comment by chrisdembia** [comment]
Great response. I can write that into the paper, unless you want to take it.

**Comment by moorepants** [comment]
@chrisdembia We need to draft up responses to the reviewers. Some of theses explanations may only need to go in the response as opposed to the paper. Some of this one can probably go in the paper. But not all. It is too long.
