### ISSUE TITLE
Explain the 's' in the 'Ls*' variables and that solids can share levels.

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#36]
From reviewer #2:

> Figure 1: The authors should give the abbreviations of the body parts. It is not obvious why all the levels for the torso does not use the P,T,C letters, but 's' instead. I understand this is the original nomenclature used by M.R. Yeadon, but this should be detailed. Moreover, as explained later in the manuscript, some segments have two levels at the same location (for example, shoulder and neck levels are abbreviated by Ls5), they would be distinguished for clarity. Thus, this would help to better understand the departures proposed (like in Acromion stadia).

**Comment by chrisdembia** [comment]
> Moreover, as explained later in the manuscript, some segments have two levels at the same location (for example, shoulder and neck levels are abbreviated by Ls5), they would be distinguished for clarity. Thus, this would help to better understand the departures proposed (like in Acromion stadia).

I agree that this would be a good change. However, this could be somewhat painful to propagate. This means updating figures and code. I have already made some effort in the code and in the figures to clarify this, falling short of coming up with a new notation for specifying two stadia at the same level. I'd rather not introduce new notation and propagate these changes. What do you say?

I'll make the first change (commenting about s vs P, T, C).

**Comment by moorepants** [comment]
Yeah, I don't want to introduce new notation either. I think it is sufficient to just state it in the paper/docs about the one shared level that has different dimensions.

**Comment by chrisdembia** [comment]
K it's already stated. Thanks.
