### ISSUE TITLE
Explain why we assume hip join center to have y, z = 0

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#40]
From reviewer 2:

> Formulas 1 and 2: These formulas give only the x coordinates of the hip center joint. What about the y and z coordinates?

**Comment by moorepants** [comment]
We assume that the hip joints are at y, z = 0. I think this is done because that is what yeadon did. We do the same with the shoulder joints. All of the joints assume this simplest joint location.

**Comment by chrisdembia** [comment]
> We assume that the hip joints are at y, z = 0. I think this is done because that is what yeadon did. We do the same with the shoulder joints. All of the joints assume this simplest joint location.

Yes.

We specify the full 3-D vector location of the hip joint centers in the paper; they just happen to only have an x component. We can state this in our response to the reviewer, but I don't think we need to make any changes to the paper. Close this issue if you agree.

**Comment by chrisdembia** [comment]
Actually, I'll clarify this in the paper.

**Comment by chrisdembia** [comment]
His comment only seems to ask us to provide y and z components, not to explain the rationale. Do you think we need to?

**Comment by chrisdembia** [comment]
We do give rationale in the paper already.

**Comment by moorepants** [comment]
Mont and I discussed this on the phone. Yeadon sets his origin mid-distance from the two hip joint centers. So that is why there are no y and z coordinates. It is simply a function of the definition of the origin of the model. If you want to clarify more, then that is fine. Otherwise, if we give the rationale clearly, leave it be and we will respond to the comment in the reviewer response.

**Comment by chrisdembia** [comment]
Check out my PR.

**Comment by moorepants** [comment]
I think we need a better clarification of the definition of the origin.

**Comment by chrisdembia** [comment]
Please review again.
