### ISSUE TITLE
Explain degenerate stadia better

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#44]
From reviewer 2:

> "Degenerate Stadia": What are the manipulations? Please detail.

**Comment by chrisdembia** [comment]
When we were working on the manuscript, I was going to detail this calculation but I couldn't understand the code so I decided to leave the text vague...hehe. K i'll try to figure out the code again.

**Comment by chrisdembia** [comment]
This might take some time.

**Comment by moorepants** [comment]
Wasn't is that you throw an error if incompatible dimensions are given?

**Comment by chrisdembia** [comment]
> Wasn't is that you throw an error if incompatible dimensions are given?

Yes, errors are thrown in this case. However, this issue is not about incompatible dimensions. It's about  compatible dimensions that cause degenerate stadia, which are fine; they just cause divide-by-zero errors that can be avoided.
