### ISSUE TITLE
Cite Python and state that this software is not Python 3 compatible

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#45]
From reviewer 2:

> "Software design": Please add a reference for "Python" as this is the only one tool that does not have one (compared to Mayavi or VTK). The authors should also indicate that the library is implemented with Python 2.7. Their code could not be compatible with Python 3.

**Comment by moorepants** [comment]
We should also "pin" versions of the other software we used.

We only test yeadon with the latest available on travis and through pip. Here are the versions of the dependencies:

Required:
- Python 2.7
- setuptools
- numpy 1.9.1
- pyyaml 3.11

Optional:
- mayavi (we don't test gui code, latest mayavi is 4.4.0)
- sphinx 1.2.3
- numpydoc 0.5
- nose 1.3.4

**Comment by moorepants** [comment]
Citing Python: http://academia.stackexchange.com/questions/5482/how-do-i-reference-the-python-programming-language-in-a-thesis-or-a-paper

**Comment by chrisdembia** [comment]
Closing this. Let me know if I was wrong to do so.
