### ISSUE TITLE
Explain how we fix the joint angle range

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#46]
From reviewer 2:

> Figure 5: How did the authors fix the joint angular range? This seems to be empirical but it should be at least mentioned in the manuscript.

**Comment by moorepants** [comment]
What should we say about this? I suspect he means that you should measure the joint angle range of your subjects and the limits should recorded.

I think we only set joint angle ranges in the GUI. The GUI values where chosen to limit to "obviously" extreme angles...although there are some nimble people out in the world that could do angles that we currently have limited in the GUI.

**Comment by chrisdembia** [comment]
> The GUI values where chosen to limit to "obviously" extreme angles

The limits match the limits in the code.

It's not really important I think. There just needs to be some limit, and the person using the model should be fully aware of the configuration they put the model in. If the model were being used to perform IK, then this could be a serious concern. I agree we can state in the paper that they were "chosen to limit to "obviously" extreme angles" or something like that.
