### ISSUE TITLE
Enable ShareLaTeX CI

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#47]
See: https://www.sharelatex.com/github

@chrisdembia Doesn't seem like I can do this with my permission level.

The nice thing is ShareLaTeX has minted so we can switch to that.

I have it setup here if you need an example: https://github.com/csu-hmc/perturbed-data-paper

**Comment by chrisdembia** [comment]
Check it out now: https://www.sharelatex.com/github/repos/chrisdembia/python-yeadon-paper

**Comment by moorepants** [comment]
Sweet, you can add the badge to the readme instead of the writelatex link.
