### ISSUE TITLE
Make a new yeadon release

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/python-yeadon-paper#48]
Due to, at least, issue #41 we will need to make a new release.

- [x] somersalt -> somersault
- [x] Fix the error reported in https://github.com/chrisdembia/python-yeadon-paper/issues/37
- [x] Update bicycle example to pin to yeadon 1.2.1.
- [x] Update zenodo release (it may happen automatically).
- [x] Update the zenodo link in the paper.
- [x] Update any references to the package number in the paper.
- [x] Make sure F1000Research updates their github repo.

**Comment by moorepants** [comment]
I'm going to start a 1.2.1 branch for yeadon.

**Comment by chrisdembia** [comment]
thank you

**Comment by moorepants** [comment]
What is this `Ls4 -> Ls4D, Ls4P (distal/proximal)` fix?

**Comment by chrisdembia** [comment]
I removed it. Was related to #36 but we agreed not to do it.

**Comment by moorepants** [comment]
The new DOI: http://dx.doi.org/10.5281/zenodo.15770
